apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: repository
      description: The git repo
    - name: revision
      description: The git repo revision
      default: master
    - name: prnumber
      description: The pullrequest number
    - name: apikey
      description: the ibmcloud api key
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        params:
        - name: pipeline-pvc
          value: pipelinerun-$(uid)-pvc
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: prnumber
          value: $(params.prnumber)
        - name: apikey
          value: $(params.apikey)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: "https://github.com/nadgowdas/gitsecure-test2"
    - name: prnumber
      value: $(event.number)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
