apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: repository
      description: the git repo
    - name: revision
      description: The git repo revision
    - name: prnumber
      description: The pullrequest number
    - name: apikey
      description: the ibmcloud api key
  tasks:
    - name: pipeline-gitsecure-discovery-task
      taskRef:
        name: gitsecure-discovery-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
    - name: pipeline-gitsecure-remediation-task
      runAfter: [pipeline-gitsecure-discovery-task]
      taskRef:
        name: gitsecure-remediation-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: prnumber
          value: $(params.prnumber)
        - name: apikey
          value: $(params.apikey)
    - name: pipeline-gitsecure-cis-task
      runAfter: [pipeline-gitsecure-discovery-task]
      taskRef:
        name: gitsecure-cis-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: prnumber
          value: $(params.prnumber)
        - name: apikey
          value: $(params.apikey)
