name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag shri4u/test
      
    - name: Scan image
      uses: anchore/scan-action@master
      with:
         image-reference: "shri4u/test" 
         dockerfile-path: ./Dockerfile   
 
